/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/withScreen.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/withScreen.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.015}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.401, -0.684, 5.72]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.ButtonA.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.ButtonB.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.ButtonX.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.ButtonY.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.LeftButton1.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.LeftButton2.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.LeftButton3.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.LeftButton4.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.LeftJoycon.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.Nintendo_Switch_Nintendo_Switch_Material_0.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.RightJoycon.geometry} material={materials['Nintendo_Switch_Material.002']} />
            <mesh geometry={nodes.Screen.geometry} material={materials['Nintendo_Switch_Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/withScreen.glb')
